export class MovimientoInterfaz {
  constructor (
  public hdgcodigo        ?: number,
  public esacodigo ?: number,
  public cmecodigo ?: number,
  public fechainicio   ?: string,
  public fechatermino  ?: string,
  public servicio ?: string,
  public servidor  ?: string,
  public usuario  ?: string,
  public fdeid  ?: number,
  public fecha  ?: string,
  public tipomovimientocuenta   ?: string,
  public tipomovimiento  ?: string,
  public identificacion  ?: string,
  public paciente  ?: string,
  public mfdemeincodmei   ?: string,
  public mfdemeinid  ?: number,
  public mfdecantidad   ?: number,
  public mfdectasid  ?: number,
  public mfdereferenciacontable  ?: number,
  public intcargoestado  ?: string,
  public intcargofecha  ?: string,
  public intcargoerror  ?: string,
  public interpestado  ?: string,
  public interpfecha  ?: string,
  public interperror  ?: string,
  public descripcionproducto ?: string,
  public camaactual ?: string,
  public codambito ?: number,
  public ctanumcuenta ?: number,
  public estadoenvio ?: string,
  public glosarespuesta ?: string,
  public numeroreceta ?: number
  ) { }
}
