import { DetalleRecetas } from './detalle-recetas';

export class Receta {
    constructor (
        public servidor             ?: string,
        public fechainicio          ?: string,
        public fechahasta           ?: string,
        public receid               ?: number,
        public hdgcodigo            ?: number,
        public esacodigo            ?: number,
        public cmecodigo            ?: number,
        public receambito           ?: number,
        public recetipo             ?: string,
        public recenumero           ?: number,
        public recesubreceta        ?: number,
        public recefecha            ?: string,
        public recefechaentrega     ?: string,
        public fichapaci            ?: number,
        public recectaid            ?: number,
        public receurgid            ?: number,
        public recedau              ?: number,
        public rececliid            ?: number,
        public recetipdocpac        ?: number,
        public recedocumpac         ?: string,
        public recetipdocprof       ?: number,
        public recedocumprof        ?: string,
        public receespecialidad     ?: string,
        public recerolprof          ?: string,
        public recesolid            ?: number,
        public receestadodespacho   ?: number,
        public recenombrepaciente   ?: string,
        public recenombremedico     ?: string,
        public rececodunidad        ?: string,
        public rececodservicio      ?: string,
        public receglosaunidad      ?: string,
        public receglosaservicio    ?: string,
        public rececodigocama       ?: string,
        public receglosacama        ?: string,
        public rececodigopieza      ?: string,
        public receglosapieza       ?: string,
        public recetipdocpacglosa   ?: string,
        public clinombres           ?: string,
        public cliapepaterno        ?: string,
        public cliapematerno        ?: string,
        public cajanumerocomprobante?: number,
        public cajaidcomprobante    ?: number,
        public cajafechacomprobante ?: string,
        public codigoestadocomprobante?: string,
        public glosaestadocomprobante?: string,
        public pestid               ?: number,
        public recetadetalle        ?: DetalleRecetas[], 
            
    ) {}
}